version: '3'
services: 
    node: 
        build: .
        ports: 
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        command: ["npm", "start"]
        image: okrypets/nodejs
        volumes: 
            - ./src:/usr/src/app/src
            - ./logs:/usr/src/app/logs
            - node_modules:/usr/node/app/node_modules
        networks: 
            - frontend
            - backend
        restart: on-failure
    postgres:
        build: ./database
        ports: 
            - 5433:${POSTGRES_PORT}
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data
        image: okrypets/postgres
        networks: 
            - backend
        volumes:  
            - ./pgdata:/var/lib/postgresql/data
        restart: on-failure
volumes: 
    logs:
    pgdata:
    node_modules:
networks:
    frontend: 
        name: frontend
        driver: bridge
    backend: 
        name: backend
        driver: bridge