version: '3'
services: 
    node: 
        build: .
        ports: 
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        environment:
            - PORT=${PORT}
    postgres:
        build: ./database
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
